"""Full-length Raymond Realty demo call transcripts (~15–18 min discovery calls)."""

from __future__ import annotations

from typing import Any

EXISTING_ID = "7d593e0a-aa11-4151-b42f-4258468098c3"
SCENARIO_IDS = [
    EXISTING_ID,
    "c41e8f20-6b2d-4a91-9f3e-2d8a7c15e401",
    "d52f9a31-7c3e-5b02-a04f-3e9b8d26f512",
    "e63a0b42-8d4f-6c13-b15a-4f0c9e37a623",
    "f74b1c53-9e50-7d24-c26b-501d0f48b734",
    "a85c2d64-af61-8e35-d37c-612e1a59c845",
    "b96d3e75-b072-9f46-e48d-723f2b6ad956",
    "c07e4f86-c183-a057-f59e-834a3c7be067",
]


def _seg(speaker_id: int, role: str, text: str, start_ms: int, end_ms: int) -> dict[str, Any]:
    return {
        "speaker_id": speaker_id,
        "role": role,
        "text": text,
        "start_ms": start_ms,
        "end_ms": end_ms,
    }


def goregaon_qualified_transcript(first: str) -> list[dict[str, Any]]:
    """~18 min Goregaon 3BHK discovery — mirrors expand_conversation.py."""
    return [
        _seg(0, "rep", f"Good afternoon, thank you for calling Raymond Realty. My name is {first}. How can I help you today?", 0, 6500),
        _seg(1, "prospect", f"Hi {first}, I saw your ad for the Goregaon project. We are looking for a three BHK with a sea view if possible.", 7000, 14500),
        _seg(0, "rep", "Great choice. May I ask what budget range you are comfortable with, and when are you planning to move in?", 15000, 21000),
        _seg(1, "prospect", "We are thinking around two crore, maybe stretch to two point two. Move-in would be within six months.", 21500, 28000),
        _seg(0, "rep", "Perfect. We have a three BHK in Tower B facing the western skyline starting at about one point nine five crore. Is Goregaon West your preferred micro-market?", 28500, 37000),
        _seg(1, "prospect", "Yes, near the station would be ideal. My office is in Andheri East so commute matters.", 37500, 43000),
        _seg(0, "rep", "Understood. The site is roughly twelve minutes from Goregaon station off the main road. Do you need two parking slots?", 43500, 50000),
        _seg(1, "prospect", "Yes, two covered parking spaces. We also want a higher floor — at least fifteenth plus for the view.", 50500, 57000),
        _seg(0, "rep", "We still have inventory on floors fifteen through twenty-two in that tower. The premium for a sea-facing unit is roughly eight to twelve lakhs depending on floor.", 57500, 66000),
        _seg(1, "prospect", "That is within range. What is the carpet area for the three BHK configuration?", 66500, 71000),
        _seg(0, "rep", "The carpet is approximately nine hundred eighty square feet with an attached deck on the living room.", 71500, 77000),
        _seg(1, "prospect", "Hmm, one point nine five sounds good but I am worried about the maintenance charges. Last project we saw had very high society fees.", 77500, 85000),
        _seg(0, "rep", "Fair concern. Maintenance here is roughly twelve rupees per square foot, and we can share the full breakup on email. It is competitive for a branded developer in this micro-market.", 85500, 94000),
        _seg(1, "prospect", "Okay. What about the payment plan? We can put down thirty percent but need flexibility on the next two tranches.", 94500, 101000),
        _seg(0, "rep", "We offer a construction-linked plan: ten percent on booking, twenty on agreement, and the balance tied to milestones. I can send a customized schedule.", 101500, 109000),
        _seg(1, "prospect", "We are also comparing Lodha's project in the same belt. How would you differentiate?", 109500, 115000),
        _seg(0, "rep", "Raymond offers lower density — four apartments per floor, dedicated club house, and possession track record in this corridor. Happy to share a side-by-side comparison sheet.", 115500, 124000),
        _seg(1, "prospect", "That would help. My wife cares a lot about kids' amenities — is there a pool and indoor play area?", 124500, 130000),
        _seg(0, "rep", "Yes, rooftop pool, indoor games room, and a co-working lounge. The sample flat is ready on site.", 130500, 136500),
        _seg(1, "prospect", "Good. Any bank tie-ups for home loans? We are pre-approved with HDFC but open to others if the rate is better.", 137000, 143500),
        _seg(0, "rep", "We have tie-ups with HDFC, ICICI, and SBI. Subvention schemes may be available depending on the tower — I will confirm with finance.", 144000, 151000),
        _seg(1, "prospect", "One more thing — is the western view actually sea view or just city skyline? That is important for us.", 151500, 157500),
        _seg(0, "rep", "Floors eighteen and above get a clear sea glimpse on the west; lower floors are predominantly skyline. I can mark the best stacks on the floor plan.", 158000, 166000),
        _seg(1, "prospect", "That clarifies it. Yes please, send the brochure, payment plan, and maintenance sheet to rajesh dot mehta at gmail.", 166500, 173000),
        _seg(0, "rep", "Will do today. If the numbers look right, would Saturday morning work for a site visit with your wife?", 173500, 179000),
        _seg(1, "prospect", "Saturday around ten works. If the sample flat matches what we discussed, we can discuss token amount on the spot.", 179500, 185500),
        _seg(0, "rep", "Excellent. I will block ten A M and share the site map and visitor pass. Thank you for your time, Rajesh — speak soon.", 186000, 192000),
    ]


def build_scenarios(rep_name: str) -> list[dict[str, Any]]:
    first = rep_name.split()[0] if rep_name else "Rep"
    return [
        {
            "id": EXISTING_ID,
            "days_ago": 3,
            "label": "Goregaon 3BHK · qualified",
            "transcript": goregaon_qualified_transcript(first),
            "suggestions": [
                {"generation_id": 1, "trigger_query": "three bhk goregaon sea view", "suggestion_text": "Confirm tower name and floor band for sea glimpse. Ask if Andheri commute is non-negotiable.", "from_cache": False, "latency_ms": 840},
                {"generation_id": 2, "trigger_query": "budget two crore move in six months", "suggestion_text": "Anchor on 1.95 Cr starting price and 6-month possession. Offer 3BHK stack comparison within 2.2 Cr cap.", "from_cache": False, "latency_ms": 920},
                {"generation_id": 3, "trigger_query": "maintenance charges society fees", "suggestion_text": "Share ₹12/sq ft maintenance with one-page society cost breakdown vs last project they saw.", "from_cache": True, "latency_ms": 120},
                {"generation_id": 4, "trigger_query": "comparing lodha same belt", "suggestion_text": "Lead with density (4 units/floor), club amenities, and possession track record — offer comparison PDF.", "from_cache": False, "latency_ms": 1100},
                {"generation_id": 5, "trigger_query": "western view sea view or skyline", "suggestion_text": "Be precise: sea glimpse from floor 18+. Propose marking best stacks on floor plan before visit.", "from_cache": False, "latency_ms": 780},
            ],
        },
        {
            "id": SCENARIO_IDS[1],
            "days_ago": 1,
            "label": "Thane West 2BHK investor · qualified",
            "transcript": [
                _seg(0, "rep", f"Good morning, Raymond Realty, {first} speaking. How may I assist you today?", 0, 5500),
                _seg(1, "prospect", "Hi, I am exploring your Thane West project for a pure investment purchase.", 6000, 11000),
                _seg(0, "rep", "Happy to help. Are you targeting rental income, capital appreciation, or both?", 11500, 17000),
                _seg(1, "prospect", "Primarily rental. I want thirty five to forty thousand monthly after possession.", 17500, 23000),
                _seg(0, "rep", "Understood. What all-in budget are you comfortable with, including registration and parking?", 23500, 29000),
                _seg(1, "prospect", "Up to one point four crore. I can close within thirty days if the yield math works.", 29500, 35500),
                _seg(0, "rep", "Our two BHK in Tower A starts around one point two five crore. Thane West two BHK rentals are typically thirty two to thirty eight thousand.", 36000, 45000),
                _seg(1, "prospect", "That band works. What is the carpet area and current construction stage?", 45500, 50000),
                _seg(0, "rep", "Carpet is roughly seven hundred sixty square feet. Structure is complete; interior fit-outs are underway.", 50500, 57500),
                _seg(1, "prospect", "When is RERA possession and is there any delay history on this tower?", 58000, 63000),
                _seg(0, "rep", "RERA possession is Q3 next year. This tower is on schedule — I can share the last four milestone certificates.", 63500, 71000),
                _seg(1, "prospect", "Good. What payment plan do you offer for investors?", 71500, 75500),
                _seg(0, "rep", "Construction-linked: ten percent booking, fifteen on agreement, balance tied to slab milestones. Possession-linked last tranche is five percent.", 76000, 84000),
                _seg(1, "prospect", "Any rental assurance or fit-out package for investors?", 84500, 88500),
                _seg(0, "rep", "We do not guarantee rent, but we share micro-market lease comps and can connect you with channel partners.", 89000, 96000),
                _seg(1, "prospect", "Fair. I am pre-approved with HDFC. Do you have a better subvention tie-up?", 96500, 101500),
                _seg(0, "rep", "HDFC, ICICI, and SBI are on panel. Subvention depends on stack — finance can share a grid today.", 102000, 108500),
                _seg(1, "prospect", "If net yield crosses three point five percent post maintenance, I can place a one lakh token this week.", 109000, 115500),
                _seg(0, "rep", "Based on current comps you should be in range. Shall I hold unit fourteen zero three on floor fourteen until Friday?", 116000, 122500),
                _seg(1, "prospect", "Yes, hold fourteen zero three. Send yield deck, payment schedule, and maintenance breakup on WhatsApp.", 123000, 129500),
                _seg(0, "rep", "Will do by six P M. Would a quick site visit Thursday evening help before you block the unit?", 130000, 135500),
                _seg(1, "prospect", "Thursday seven P M works. If the sample flat and numbers match, token can happen on visit.", 136000, 141500),
                _seg(0, "rep", "Blocked. I will share visitor pass and tower access map. Thank you for your time.", 142000, 146500),
            ],
            "suggestions": [
                {"generation_id": 1, "trigger_query": "thane two bhk rental yield", "suggestion_text": "Share net yield after ₹12/sq ft maintenance and stamp duty.", "from_cache": False, "latency_ms": 790},
                {"generation_id": 2, "trigger_query": "rera possession q3 next year", "suggestion_text": "Attach milestone certificates to build investor confidence.", "from_cache": False, "latency_ms": 650},
            ],
        },
        {
            "id": SCENARIO_IDS[2],
            "days_ago": 5,
            "label": "Dadar 3BHK sea-facing · qualified",
            "transcript": [
                _seg(0, "rep", f"Raymond Realty, {first} here. Thank you for calling — how can I help?", 0, 5000),
                _seg(1, "prospect", "We shortlisted your Dadar three BHK online. Is the sea-facing stack still available?", 5500, 10500),
                _seg(0, "rep", "Yes, limited sea-facing inventory remains in Tower D. May I know who the decision makers are?", 11000, 17000),
                _seg(1, "prospect", "My husband Anil and I. Budget up to three crore all inclusive with two parking.", 17500, 23500),
                _seg(0, "rep", "The sea-facing three BHK is around two point eight five crore plus floor rise. Does that fit your all-in cap?", 24000, 31000),
                _seg(1, "prospect", "It is tight but workable if stamp duty benefits apply this quarter.", 31500, 36000),
                _seg(0, "rep", "I will loop finance for the stamp duty note. What carpet area are you expecting?", 36500, 41500),
                _seg(1, "prospect", "At least one thousand one hundred square feet carpet for a family of four.", 42000, 47000),
                _seg(0, "rep", "This layout is one thousand fifty carpet with a wide deck. I can share CAD plans tonight for your architect.", 47500, 54500),
                _seg(1, "prospect", "Architect review is mandatory before we visit. What about society maintenance?", 55000, 60000),
                _seg(0, "rep", "Maintenance is fourteen rupees per square foot with a sinking fund schedule. Competitive for Dadar branded stock.", 60500, 68000),
                _seg(1, "prospect", "We are also looking at a Wadhwa project nearby. Why Raymond?", 68500, 73000),
                _seg(0, "rep", "Lower density, four units per floor, full-height lobby, and Raymond's delivery record in this belt. I can send a comparison sheet.", 73500, 81500),
                _seg(1, "prospect", "Kids' amenities matter — pool, indoor play, and security?", 82000, 86500),
                _seg(0, "rep", "Rooftop pool, indoor games, kids' zone, and twenty four seven security with CCTV across common areas.", 87000, 93500),
                _seg(1, "prospect", "What is the payment plan if we book this month?", 94000, 98000),
                _seg(0, "rep", "Ten percent booking, twenty agreement, balance milestone-linked. Festive waiver on floor rise may apply on select stacks.", 98500, 106000),
                _seg(1, "prospect", "Send CAD plans, stamp duty note, and maintenance sheet to anil dot shah at outlook dot com.", 106500, 112500),
                _seg(0, "rep", "Will do tonight. If architect approves, would Sunday eleven A M work for a joint visit?", 113000, 118500),
                _seg(1, "prospect", "Send plans first. If layout works, Sunday eleven is likely with our architect on call.", 119000, 124500),
                _seg(0, "rep", "Noted. I will calendar a tentative slot and share the visitor briefing pack. Thank you, Anil and Priya.", 125000, 130500),
            ],
            "suggestions": [
                {"generation_id": 1, "trigger_query": "dadar sea facing three bhk", "suggestion_text": "Share deck dimensions and floor-rise waiver eligibility before architect review.", "from_cache": False, "latency_ms": 880},
            ],
        },
        {
            "id": SCENARIO_IDS[3],
            "days_ago": 8,
            "label": "Thane vs Lodha Palava · follow-up",
            "transcript": [
                _seg(0, "rep", f"Good afternoon, {first} from Raymond Realty. You had enquired on our Thane West two BHK — is now a good time?", 0, 7000),
                _seg(1, "prospect", "Yes. I am actively comparing your project with Lodha Palava on possession and all-in cost.", 7500, 13500),
                _seg(0, "rep", "Happy to walk through it. What possession timeline do you need for your family?", 14000, 19500),
                _seg(1, "prospect", "Before December this year. Palava is quoting March next year with a flexi payment plan.", 20000, 26000),
                _seg(0, "rep", "Our RERA possession is April next year — about three months later. What configuration and budget are you targeting?", 26500, 34000),
                _seg(1, "prospect", "Two BHK around one point one crore all in. Palava is offering subvention at eight point nine percent.", 34500, 40500),
                _seg(0, "rep", "We can check ICICI subvention grids. Raymond offers lower density — four units per floor versus Palava's higher towers.", 41000, 49000),
                _seg(1, "prospect", "Density helps, but I need written confirmation on delay penalty and exact loan rate.", 49500, 55000),
                _seg(0, "rep", "Fair ask. I will request legal for the delay clause and finance for a rate sheet by tomorrow.", 55500, 62000),
                _seg(1, "prospect", "Your maintenance also looks higher than Palava. What is the per square foot charge?", 62500, 67500),
                _seg(0, "rep", "Twelve rupees per square foot plus sinking fund. I can share a side-by-side society cost comparison.", 68000, 74500),
                _seg(1, "prospect", "Please include five-year society outgo and parking charges in that sheet.", 75000, 79500),
                _seg(0, "rep", "Absolutely. Any concerns on commute or schools in Thane West?", 80000, 84500),
                _seg(1, "prospect", "Schools are fine. Commute to BKC matters — how realistic is it in morning peak?", 85000, 90500),
                _seg(0, "rep", "Eastern Express Highway access typically forty five to sixty five minutes to BKC depending on start time.", 91000, 98000),
                _seg(1, "prospect", "That is borderline. Palava shuttle claims faster access to the highway.", 98500, 103500),
                _seg(0, "rep", "I can share a time-stamped commute note from the site at peak hour for a fair comparison.", 104000, 110000),
                _seg(1, "prospect", "Do that. No site visit until loan rate, maintenance, and penalty clause are documented.", 110500, 116500),
                _seg(0, "rep", "Understood. Once you review the pack, can we schedule next Tuesday evening?", 117000, 122000),
                _seg(1, "prospect", "Let me see numbers first. If gap versus Palava is small, Tuesday could work.", 122500, 128000),
                _seg(0, "rep", "Will send everything by tomorrow noon. Thank you for the detailed questions.", 128500, 133500),
            ],
            "suggestions": [
                {"generation_id": 1, "trigger_query": "lodha palava possession subvention", "suggestion_text": "Lead with ICICI subvention grid and legal delay clause in one PDF.", "from_cache": False, "latency_ms": 940},
                {"generation_id": 2, "trigger_query": "maintenance higher than palava", "suggestion_text": "Include 5-year society outgo and parking in side-by-side cost sheet.", "from_cache": False, "latency_ms": 720},
            ],
        },
        {
            "id": SCENARIO_IDS[4],
            "days_ago": 12,
            "label": "Powai 2BHK pricing · follow-up",
            "transcript": [
                _seg(0, "rep", f"Raymond Realty Powai desk, {first} speaking. How may I help you today?", 0, 5500),
                _seg(1, "prospect", "Your Powai two BHK listing mentions sea glimpse but the price feels high for the carpet quoted.", 6000, 12000),
                _seg(0, "rep", "I can clarify. What carpet size and all-in budget are you working with?", 12500, 17500),
                _seg(1, "prospect", "At least nine hundred square feet carpet under one point eight crore including parking.", 18000, 23500),
                _seg(0, "rep", "Our stack is eight hundred forty carpet at one point nine crore base for partial western glimpse.", 24000, 30500),
                _seg(1, "prospect", "That is a stretch. Does festive discount apply and can parking be bundled?", 31000, 36000),
                _seg(0, "rep", "Select stacks have up to three lakhs festive benefit. One covered parking is included; second is eight lakhs.", 36500, 44000),
                _seg(1, "prospect", "I need clarity on floor rise charges and whether the view is guaranteed in writing.", 44500, 50000),
                _seg(0, "rep", "Floor rise is six thousand per floor from the fourth. View photos are stack-specific — I can share daylight shots.", 50500, 58000),
                _seg(1, "prospect", "We are also speaking to Hiranandani for a slightly larger carpet at similar pricing.", 58500, 64000),
                _seg(0, "rep", "Raymond offers lower density and a younger tower with smart home package on select units. Happy to compare all-in costs.", 64500, 72000),
                _seg(1, "prospect", "Send stack-wise photos, floor rise grid, and all-in cost with taxes. My wife decides jointly.", 72500, 78500),
                _seg(0, "rep", "Will do today. Would a weekend visit help if the view photos look right?", 79000, 84000),
                _seg(1, "prospect", "Let me review with her first. If discount and view check out, we may visit next weekend.", 84500, 90500),
                _seg(0, "rep", "Fair. Any other blockers — maintenance, loan, or possession timing?", 91000, 95500),
                _seg(1, "prospect", "Possession is fine. Maintenance and total EMI after discount are the real decision drivers.", 96000, 101500),
                _seg(0, "rep", "I will include maintenance at thirteen rupees per square foot and an EMI snapshot with HDFC at eight point seven five.", 102000, 109500),
                _seg(1, "prospect", "Good. Email everything to sneha dot rao at gmail. We will call back next week.", 110000, 115500),
                _seg(0, "rep", "Sent by tonight. Thank you, Sneha — I will follow up Wednesday if I do not hear back.", 116000, 121000),
            ],
            "suggestions": [
                {"generation_id": 1, "trigger_query": "powai sea glimpse carpet price", "suggestion_text": "Present all-in sheet: base, floor rise, parking, stamp duty, and EMI.", "from_cache": False, "latency_ms": 810},
            ],
        },
        {
            "id": SCENARIO_IDS[5],
            "days_ago": 16,
            "label": "Pune Kharadi budget mismatch · at risk",
            "transcript": [
                _seg(0, "rep", f"Good evening, Raymond Realty Pune, {first} here. How can I assist?", 0, 5500),
                _seg(1, "prospect", "I saw Kharadi pricing online. It looks well above my one crore all-in budget.", 6000, 11000),
                _seg(0, "rep", "Thanks for sharing that upfront. Which configuration are you considering?", 11500, 16000),
                _seg(1, "prospect", "Two BHK with two parking, but only if total stays under one crore including registration.", 16500, 22000),
                _seg(0, "rep", "Kharadi two BHK starts at one point one five crore plus floor rise. We also have a compact two BHK at ninety eight lakhs in Tower C.", 22500, 31000),
                _seg(1, "prospect", "Ninety eight is still tight and the compact layout may not work for our family of four.", 31500, 37000),
                _seg(0, "rep", "The compact unit is seven hundred ten carpet. Standard two BHK is eight hundred twenty carpet from one point one five.", 37500, 45000),
                _seg(1, "prospect", "What festive benefit exists? Any stack under ninety five lakhs all in?", 45500, 50000),
                _seg(0, "rep", "Festive benefit up to two lakhs on select Tower C stacks. All-in under ninety five is unlikely for two parking.", 50500, 58000),
                _seg(1, "prospect", "Then EMI crosses forty thousand even with longest tenure. That is a hard stop for us.", 58500, 64500),
                _seg(0, "rep", "Understood. We could explore one parking or a higher floor rise waiver, but base price is firm on premium stacks.", 65000, 72000),
                _seg(1, "prospect", "We cannot compromise on two parking. What about alternate locations within Raymond?", 72500, 78000),
                _seg(0, "rep", "Wagholi has a two BHK closer to ninety two lakhs but possession is later. Commute to Kharadi IT parks is longer.", 78500, 86000),
                _seg(1, "prospect", "Wagholi commute will not work. I think this is a mismatch unless something sub ninety five appears.", 86500, 92500),
                _seg(0, "rep", "I will note your criteria. If Tower C festival inventory opens, I can alert you once.", 93000, 99000),
                _seg(1, "prospect", "Please do not call repeatedly. Email only if a true sub ninety five lakh two BHK with two parking exists.", 99500, 106500),
                _seg(0, "rep", "Noted respectfully. Thank you for the clarity today.", 107000, 111000),
            ],
            "suggestions": [
                {"generation_id": 1, "trigger_query": "budget one crore two parking", "suggestion_text": "Qualify all-in budget before sea-facing pitch; pivot to Wagholi earlier.", "from_cache": False, "latency_ms": 690},
            ],
        },
        {
            "id": SCENARIO_IDS[6],
            "days_ago": 20,
            "label": "Borivali rushed enquiry · at risk (rep-heavy)",
            "transcript": [
                _seg(1, "prospect", "I have five minutes. What is the starting price for your Borivali two BHK?", 0, 6000),
                _seg(0, "rep", f"Sure, {first} from Raymond. Borivali is a flagship corridor project with rooftop pool, sky lounge, co-working pavilion, landscaped podium, indoor games, kids' play courts, banquet lawn, and premium fittings across three towers with strong Western Express Highway connectivity.", 6500, 18500),
                _seg(1, "prospect", "I asked for starting price, not the full brochure.", 19000, 22500),
                _seg(0, "rep", "Apologies. Entry two BHK is ninety five lakhs plus taxes on lower floors. Higher floors with park view go up to one point three crore depending on stack, floor rise, parking, club membership, and smart home package.", 23000, 32000),
                _seg(1, "prospect", "What is carpet area on the ninety five lakh unit?", 32500, 35500),
                _seg(0, "rep", "Before I answer — Raymond has delivered consistently in Mumbai since nineteen eighty with award-winning club design and low-density living.", 36000, 43000),
                _seg(1, "prospect", "Carpet area please.", 43500, 45500),
                _seg(0, "rep", "Seven hundred twenty square feet carpet with dry balcony. The clubhouse alone is twenty two thousand square feet with pool and gym.", 46000, 53000),
                _seg(1, "prospect", "Is metro walking distance or not?", 53500, 56000),
                _seg(0, "rep", "Metro phase two will improve connectivity. Today autos and buses are frequent, and the project has school tie-ups nearby.", 56500, 63500),
                _seg(1, "prospect", "That is not a yes or no. Give exact distance to the nearest metro station.", 64000, 68500),
                _seg(0, "rep", "Current nearest station is about two point eight kilometers; planned line reduces it once operational.", 69000, 75000),
                _seg(1, "prospect", "Maintenance per square foot and all-in cost for the entry stack?", 75500, 79500),
                _seg(0, "rep", "Maintenance eleven rupees per square foot. All-in with registration and one parking is roughly one point zero six crore on the entry stack.", 80000, 87500),
                _seg(1, "prospect", "Send that breakdown on email only. This call was not efficient — too much pitching.", 88000, 93500),
                _seg(0, "rep", "I understand. I will email the all-in sheet and metro map tonight.", 94000, 98500),
                _seg(1, "prospect", "Do not call again unless the email answers every number I asked.", 99000, 103000),
                _seg(0, "rep", "Understood. Thank you for your time.", 103500, 106500),
            ],
            "suggestions": [
                {"generation_id": 1, "trigger_query": "borivali starting price five minutes", "suggestion_text": "Lead with price, carpet, metro distance — save amenities until asked.", "from_cache": False, "latency_ms": 540},
            ],
        },
        {
            "id": SCENARIO_IDS[7],
            "days_ago": 24,
            "label": "Navi Mumbai Ulwe research · nurture",
            "transcript": [
                _seg(0, "rep", f"Raymond Realty Navi Mumbai, {first} speaking. How may I help?", 0, 5000),
                _seg(1, "prospect", "I am researching Ulwe and Panvel for next year. Not buying immediately.", 5500, 10000),
                _seg(0, "rep", "Happy to help you plan. What configuration and rough budget are you exploring?", 10500, 15500),
                _seg(1, "prospect", "Maybe two BHK. Budget still forming — likely one to one point two crore when we decide.", 16000, 21500),
                _seg(0, "rep", "When do you expect to firm up timeline — post monsoon next year as many families do?", 22000, 27000),
                _seg(1, "prospect", "Yes, after monsoon. Commute to BKC is the main filter.", 27500, 31500),
                _seg(0, "rep", "Ulwe connects via Palm Beach Road and upcoming metro. Peak BKC commute can be seventy to ninety minutes.", 32000, 39000),
                _seg(1, "prospect", "That is acceptable if schools and hospitals are nearby. What does Raymond offer in Ulwe?", 39500, 45000),
                _seg(0, "rep", "Two BHK from roughly ninety eight lakhs, clubhouse, pool, kids' areas, and possession in eighteen months on current schedule.", 45500, 53000),
                _seg(1, "prospect", "Payment plan for planning purposes only?", 53500, 56500),
                _seg(0, "rep", "Construction-linked with ten percent booking and milestone tranches. I can share a sample schedule without booking pressure.", 57000, 64000),
                _seg(1, "prospect", "Any airport or SEZ employment angle that helps resale?", 64500, 68500),
                _seg(0, "rep", "Navi Mumbai airport work and Ulwe SEZ proximity support long-term demand. I can include a resale note in the pack.", 69000, 76000),
                _seg(1, "prospect", "Send soft copy only — commute matrix, sample payment plan, and amenity list. No site visit now.", 76500, 82500),
                _seg(0, "rep", "Absolutely. Would a check-in after two months work once you have compared BKC commute options?", 83000, 88500),
                _seg(1, "prospect", "Yes, email first and call in October if we are still active.", 89000, 93500),
                _seg(0, "rep", "Will do. Thank you for the early research call — I will send the overview today.", 94000, 99000),
            ],
            "suggestions": [],
        },
    ]
